const rates={D:0,E:80,L:80,N:100,R:0,PH:0,AL:0,BL:0},off=['R','PH','AL','BL'],colors={D:'#2563eb',E:'#b45309',L:'#0891b2',N:'#7c3aed',R:'#059669',PH:'#e11d48',AL:'#65a30d',BL:'#ca8a04'};
const types=Object.keys(rates).map((code,i)=>({id:i+1,code,name:code,color:colors[code],allowance:rates[code],is_off:off.includes(code)?1:0}));
const validDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const validMonth=v=>typeof v==='string'&&/^20\d{2}-(0[1-9]|1[0-2])$/.test(v);
const length=v=>[...v].length,enc=new TextEncoder();const rand=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
const nameFor=(name,code)=>!name||name===code||name==='รหัส '+code?'ยังไม่มีชื่อจริง':name;
function fail(message,status=422){throw Object.assign(new Error(message),{status});}
function req(d,k,max=150){const v=typeof d[k]==='string'?d[k].trim():'';if(!v||length(v)>max)fail('กรุณากรอก '+({real_name:'ชื่อจริง',title:'หัวข้อ',employee_code:'รหัสพนักงาน',name:'ชื่อ'}[k]||k)+' ไม่เกิน '+max+' ตัวอักษร');return v;}
function checkPass(v){if(typeof v!=='string'||length(v)<6||enc.encode(v).length>72||v.includes('\0'))fail('รหัสผ่านอย่างน้อย 6 ตัวอักษร และไม่เกิน 72 ไบต์');}
async function digest(v){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(v))),b=>b.toString(16).padStart(2,'0')).join('');}
async function passwordHash(v,salt=rand().slice(0,32)){const key=await crypto.subtle.importKey('raw',enc.encode(v),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100000},key,256);return 'pbkdf2$'+salt+'$'+Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,'0')).join('');}
async function verify(v,hash){const got=await passwordHash(v,hash?.split('$')[1]||'invalid');if(got.length!==hash?.length)return false;let n=0;for(let i=0;i<got.length;i++)n|=got.charCodeAt(i)^hash.charCodeAt(i);return n===0;}
const safeUser=u=>({id:u.id,employee_code:u.employee_code,name:u.name,nickname:u.nickname,roster_name:u.roster_name,role:u.role,recovery_question:u.recovery_question,session_version:u.session_version});
function summary(events){const s={total:0,work_days:0,off_days:0,missing_days:0,breakdown:{}};for(const [code,rate] of Object.entries(rates))s.breakdown[code]={days:0,rate,total:0};for(const e of events){if(!Object.hasOwn(rates,e.code)){s.missing_days++;continue;}s.breakdown[e.code].days++;s.breakdown[e.code].total+=rates[e.code];s.total+=rates[e.code];if(off.includes(e.code))s.off_days++;else s.work_days++;}return s;}
export async function handle(request,db){let extra={},session,requestRevisions=null;try{
if(!db)fail('ฐานข้อมูลยังไม่พร้อม กรุณาลองอีกครั้ง',503);
const url=new URL(request.url),action=url.searchParams.get('action')||'me';const all=async(sql,args=[])=> (await db.prepare(sql).bind(...args).all()).results;const one=async(sql,args=[])=>db.prepare(sql).bind(...args).first();const run=async(sql,args=[])=>db.prepare(sql).bind(...args).run();const stmt=(sql,args=[])=>db.prepare(sql).bind(...args);
const now=Math.floor(Date.now()/1000),cookie=request.headers.get('cookie')?.match(/(?:^|;\s*)shifttrack_session=([a-f0-9]{64})/)?.[1];session=cookie?await one('SELECT * FROM sessions WHERE token=? AND expires>?',[await digest(cookie),now]):null;
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...extra}});
async function newSession(uid=null,version=0){const token=rand(),csrf=rand();await run('INSERT INTO sessions(token,uid,version,csrf,expires) VALUES(?,?,?,?,?)',[await digest(token),uid,version,csrf,now+7200]);extra['Set-Cookie']='shifttrack_session='+token+'; Path=/; HttpOnly; SameSite=Lax; Max-Age=7200'+(url.protocol==='https:'?'; Secure':'');return {csrf};}
async function mutate(ids,statements){ids=[...new Set(ids)].sort((a,b)=>a-b);const guards=[];for(const id of ids){const revision=requestRevisions?.get(id);if(revision===undefined)fail('ไม่พบบัญชี');guards.push(stmt('INSERT INTO mutation_guards(user_id,revision) VALUES(?,?)',[id,revision]),stmt('UPDATE users SET data_revision=data_revision+1 WHERE id=?',[id]));}try{return await db.batch([...guards,...statements]);}catch(e){if(String(e).includes('mutation_guards'))fail('ข้อมูลเปลี่ยนจากอีกเครื่องแล้ว กรุณารีเฟรชก่อนบันทึก',409);throw e;}}
const readBatch=async queries=>(await db.batch(queries.map(([sql,args=[]])=>stmt(sql,args)))).map(r=>r.results);
const getUsers=()=>all('SELECT id,employee_code,roster_name,name,nickname,role,active FROM users WHERE active=1 ORDER BY id');
async function getPeers(u,date,includeHidden=false){const own=await one('SELECT * FROM schedules WHERE user_id=? AND work_date=?',[u.id,date]);if(!own||off.includes(own.code))return {date,people:[],has_shift:!!own,is_off:!!own&&off.includes(own.code)};
const [actual,rosters,added,names,users,hidden]=await readBatch([['SELECT u.employee_code,u.nickname,s.code FROM users u JOIN schedules s ON s.user_id=u.id WHERE s.work_date=? AND u.active=1',[date]],['SELECT roster_json FROM user_roster_days WHERE user_id=? AND work_date=?',[u.id,date]],['SELECT employee_code,real_name FROM user_added_coworkers WHERE user_id=? AND work_date=? AND shift_code=?',[u.id,date,own.code]],['SELECT employee_code,real_name FROM user_coworker_names WHERE user_id=?',[u.id]],['SELECT employee_code,nickname FROM users WHERE active=1'],['SELECT employee_code FROM user_hidden_coworkers WHERE user_id=? AND work_date=? AND hidden=1',[u.id,date]]]);const roster=rosters[0];const map=new Map();if(roster){for(const r of JSON.parse(roster.roster_json)){const a=actual.find(x=>x.employee_code===r.employee);if((a?.code||r.code)===own.code&&r.employee!==u.employee_code)map.set(r.employee,{employee_code:r.employee,name:nameFor(r.name,r.employee)});}}else{for(const p of JSON.parse(own.coworker_json||'[]'))if(p.employee_code!==u.employee_code&&(!actual.find(x=>x.employee_code===p.employee_code)||actual.find(x=>x.employee_code===p.employee_code).code===own.code))map.set(p.employee_code,p);}
// Imported rows define team membership; registered schedules only update those rows.
if(!roster&&!own.coworker_json)for(const p of actual)if(p.code===own.code&&p.employee_code!==u.employee_code&&!map.has(p.employee_code))map.set(p.employee_code,{employee_code:p.employee_code,name:'ยังไม่มีชื่อจริง'});
for(const p of added)map.set(p.employee_code,{employee_code:p.employee_code,name:p.real_name,manual:true});
for(const p of map.values()){p.name=names.find(n=>n.employee_code===p.employee_code)?.real_name||nameFor(p.name,p.employee_code);p.nickname=users.find(n=>n.employee_code===p.employee_code)?.nickname||'';}
if(!includeHidden)for(const p of hidden)map.delete(p.employee_code);return {date,people:[...map.values()],has_shift:true,is_off:false};}
const getActions=['session','me','dashboard','admin-data','coworkers','coworker-options'];const posts=['register','login','recovery-question','question-settings','question-recover','recover','recovery-code','logout','password','nickname','schedule','prepare-import','commit-import','coworker-name','coworker-remove','coworker-add','training-edit','training-add','training-remove','training','delete-training','create-user','user-settings','fresh-start','demo-init'];
if(request.method==='GET'&&action==='session'){if(!session)return json(await newSession());return json({csrf:session.csrf});}
let d={};if(request.method==='POST'){const raw=await request.text();if(!posts.includes(action))fail('ไม่พบรายการ',404);if(!session||request.headers.get('X-CSRF-Token')!==session.csrf)fail('กรุณารีเฟรชหน้าเว็บก่อนทำรายการ',403);if(enc.encode(raw).length>1500000)fail('ข้อมูลใหญ่เกินไป');try{d=JSON.parse(raw);}catch{fail('ข้อมูลไม่ถูกต้อง');}if(!d||typeof d!=='object'||Array.isArray(d))fail('ข้อมูลไม่ถูกต้อง');if(request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)fail('ที่มาคำขอไม่ถูกต้อง',403);
}else if(request.method!=='GET')fail('Method not allowed',405);else if(!getActions.includes(action))fail('ไม่พบรายการ',404);
async function throttle(key,limit=10){key=await digest(key);await run('INSERT INTO auth_throttles(identity_hash,failures,window_start) VALUES(?,1,?) ON CONFLICT(identity_hash) DO UPDATE SET failures=CASE WHEN window_start<? THEN 1 ELSE failures+1 END,window_start=CASE WHEN window_start<? THEN ? ELSE window_start END',[key,now,now-900,now-900,now]);const t=await one('SELECT failures FROM auth_throttles WHERE identity_hash=?',[key]);if(t.failures>limit)fail('ทำรายการบ่อยเกินไป กรุณารอ 15 นาที',429);return key;}
if(action==='demo-init'){
 if(!['127.0.0.1','localhost'].includes(url.hostname))fail('ปิดการสร้างข้อมูลทดสอบบนเว็บใช้งานจริงแล้ว',403);
 if((await one('SELECT COUNT(*) n FROM users')).n)fail('เตรียมข้อมูล Demo แล้ว กรุณาเข้าสู่ระบบ',409);
 const pass=await passwordHash('Demo87654321'),adminPass=await passwordHash('DemoAdmin87654321');const init=[];for(const [code,name,nick,role,hash] of [['DEMOADMIN','ผู้ดูแล Demo','ผู้ดูแล','admin',adminPass],['300001','สมาชิก Demo หนึ่ง','หนึ่ง','employee',pass],['300002','สมาชิก Demo สอง','สอง','employee',pass],['300003','สมาชิก Demo สาม','สาม','employee',pass]])init.push(stmt('INSERT INTO users(employee_code,name,nickname,roster_name,role,password_hash) VALUES(?,?,?,?,?,?)',[code,name,nick,'ID:'+code,role,hash]));await db.batch(init);const users=await getUsers(),member=users.find(u=>u.employee_code==='300001');const month=validMonth(d.month)?d.month:'2026-10';const pattern=['E','R','R','E','E','E','E','E','R','R','PH','D','N','D','D','R','R','PH','L','L','L','L','L','R','R','D','D','D','D','D','R'];const end=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate(),rows=[];for(let day=1;day<=end;day++){const date=month+'-'+String(day).padStart(2,'0');for(const [i,u] of users.filter(x=>x.role==='employee').entries())rows.push({employee:u.employee_code,name:'ชื่อจริงสมาชิก Demo '+(i+1),date,code:i===0?pattern[day-1]:i===1?'E':day%3===0?'N':'E'});}const ops=[];for(const r of rows){const u=users.find(u=>u.employee_code===r.employee);ops.push(stmt('INSERT INTO schedules(user_id,work_date,code) VALUES(?,?,?)',[u.id,r.date,r.code]));}for(let day=1;day<=end;day++){const date=month+'-'+String(day).padStart(2,'0');ops.push(stmt('INSERT INTO user_roster_days(user_id,work_date,roster_json) VALUES(?,?,?)',[member.id,date,JSON.stringify(rows.filter(r=>r.date===date))]));}for(let i=0;i<ops.length;i+=75)await db.batch(ops.slice(i,i+75));for(const day of [12,14,15,30]){const date=month+'-'+day;if(day>end)continue;await run('INSERT INTO training_events(work_date,title) VALUES(?,?)',[date,'อบรม Demo วันที่ '+day]);await run('INSERT INTO training_participants(training_id,user_id) VALUES((SELECT id FROM training_events WHERE work_date=? AND title=?),?)',[date,'อบรม Demo วันที่ '+day,member.id]);}return json({ok:true});
}
function answerValue(v){const answer=String(v||'').normalize('NFKC').trim().toLowerCase().replace(/\s+/g,' ');checkPass(answer);return answer;}
if(action==='recovery-question'){const code=req(d,'employee_code',50);await throttle('question-lookup|'+(request.headers.get('CF-Connecting-IP')||'local'),20);const user=await one('SELECT recovery_question FROM users WHERE employee_code=? AND active=1',[code]);return json({question:user?.recovery_question||'คำถามกู้บัญชีที่คุณตั้งไว้'});}
if(action==='question-recover'){
 const code=req(d,'employee_code',50);await throttle('question-reset-ip|'+(request.headers.get('CF-Connecting-IP')||'local'),20);await throttle('question-reset-account|'+code,5);
 const user=await one('SELECT id,recovery_answer_hash,session_version FROM users WHERE employee_code=? AND active=1',[code]);const answer=answerValue(d.answer);if(!await verify(answer,user?.recovery_answer_hash)||!user?.recovery_answer_hash)fail('รหัสพนักงานหรือคำตอบไม่ถูกต้อง หรือยังไม่ได้ตั้งคำถามกู้บัญชี');
 checkPass(d.password);if(d.password!==d.password_confirm)fail('รหัสผ่านยืนยันไม่ตรงกัน');const r=await run('UPDATE users SET password_hash=?,session_version=session_version+1,data_revision=data_revision+1 WHERE id=? AND active=1 AND recovery_answer_hash=? AND session_version=?',[await passwordHash(d.password),user.id,user.recovery_answer_hash,user.session_version]);if(r.meta.changes!==1)fail('ข้อมูลบัญชีเปลี่ยนแล้ว กรุณาลองใหม่',409);return json({ok:true});
}
if(action==='register'){const code=req(d,'employee_code',20),nickname=String(d.nickname||'').trim(),name='สมาชิก '+code;checkPass(d.password);if(!/^\d{1,20}$/.test(code))fail('รหัสพนักงานต้องเป็นตัวเลข');if(length(nickname)>50)fail('ชื่อเล่นไม่เกิน 50 ตัวอักษร');if(d.password!==d.password_confirm)fail('รหัสผ่านยืนยันไม่ตรงกัน');await throttle('register|'+(request.headers.get('CF-Connecting-IP')||'local'));if(await one('SELECT id FROM users WHERE employee_code=?',[code]))fail('รหัสพนักงานนี้มีบัญชีแล้ว');const question=req(d,'question'),answer=answerValue(d.answer);if(answer!==answerValue(d.answer_confirm))fail('คำตอบยืนยันไม่ตรงกัน');const recovery=rand().slice(0,32).toUpperCase();await run('INSERT INTO users(employee_code,name,nickname,roster_name,password_hash,recovery_hash,recovery_question,recovery_answer_hash) VALUES(?,?,?,?,?,?,?,?)',[code,name,nickname,'ID:'+code,await passwordHash(d.password),await digest(recovery),question,await passwordHash(answer)]);return json({ok:true,recovery_code:recovery.match(/.{8}/g).join('-')});}
if(action==='recover'){
 const code=req(d,'employee_code',50);await throttle('recover|'+(request.headers.get('CF-Connecting-IP')||'local'),30);await throttle('recover-account|'+code,10);
 const recovery=String(d.recovery_code||'').toUpperCase().replace(/[\s-]/g,'');const user=await one('SELECT id,recovery_hash FROM users WHERE employee_code=? AND active=1',[code]);const hash=await digest(recovery);
 if(!/^[A-F0-9]{32}$/.test(recovery)||!user?.recovery_hash||hash!==user.recovery_hash)fail('รหัสพนักงานหรือรหัสกู้คืนไม่ถูกต้อง',422);
 checkPass(d.password);if(d.password!==d.password_confirm)fail('รหัสผ่านยืนยันไม่ตรงกัน');const next=rand().slice(0,32).toUpperCase();
 const result=await run('UPDATE users SET password_hash=?,recovery_hash=?,session_version=session_version+1,data_revision=data_revision+1 WHERE id=? AND recovery_hash=? AND active=1',[await passwordHash(d.password),await digest(next),user.id,hash]);if(result.meta.changes!==1)fail('รหัสกู้คืนถูกใช้หรือเปลี่ยนแล้ว กรุณาใช้รหัสล่าสุด',409);
 return json({ok:true,recovery_code:next.match(/.{8}/g).join('-')});
}
if(action==='login'){const code=req(d,'username',50);const key=await throttle('login|'+(request.headers.get('CF-Connecting-IP')||'local')+'|'+code);const user=await one('SELECT * FROM users WHERE employee_code=? AND active=1',[code]);if(!await verify(String(d.password||''),user?.password_hash)||!user)fail('รหัสพนักงานหรือรหัสผ่านไม่ถูกต้อง หรือบัญชีถูกปิดใช้',401);await run('DELETE FROM auth_throttles WHERE identity_hash=?',[key]);await run('DELETE FROM sessions WHERE token=?',[session.token]);await newSession(user.id,user.session_version);return json({ok:true});}
const u=session?.uid?await one('SELECT * FROM users WHERE id=? AND active=1',[session.uid]):null;if(!u||u.session_version!==session.version)fail('กรุณาเข้าสู่ระบบ',401);
if(request.method==='POST')requestRevisions=new Map((await all('SELECT id,data_revision FROM users')).map(x=>[x.id,x.data_revision]));
if(action==='fresh-start'){
 if(u.role!=='admin'||u.id!==1||u.employee_code!=='DEMOADMIN')fail('ไม่สามารถล้างข้อมูลชุดเริ่มต้นนี้ได้',403);
 if(d.confirmation!=='START EMPTY TEAM')fail('กรุณายืนยันการล้างข้อมูล');
 await throttle('fresh-start|'+u.id,5);if(!await verify(String(d.password||''),u.password_hash))fail('รหัสผ่านปัจจุบันไม่ถูกต้อง',403);
 const tables=['training_participants','training_events','schedules','imports','user_roster_days','user_added_coworkers','user_hidden_coworkers','user_coworker_names','mutation_guards','sessions','auth_throttles'];
 await db.batch([...tables.map(table=>stmt('DELETE FROM '+table)),stmt('DELETE FROM users WHERE id<>?',[u.id]),stmt("UPDATE users SET employee_code='ADMIN',name='ผู้ดูแลระบบ',nickname='ผู้ดูแล',roster_name='ID:ADMIN',active=1,session_version=session_version+1,data_revision=0,recovery_hash=NULL,recovery_question=NULL,recovery_answer_hash=NULL WHERE id=?",[u.id])]);
 extra['Set-Cookie']='shifttrack_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0';return json({ok:true,username:'ADMIN'});
}
if(action==='me')return json({user:safeUser(u),csrf:session.csrf});
if(action==='logout'){await run('DELETE FROM sessions WHERE token=?',[session.token]);extra['Set-Cookie']='shifttrack_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0';return json({ok:true});}
if(action==='question-settings'){await throttle('question-settings|'+u.id,10);if(!await verify(String(d.password||''),u.password_hash))fail('รหัสผ่านปัจจุบันไม่ถูกต้อง');const question=req(d,'question'),answer=answerValue(d.answer);if(answer!==answerValue(d.answer_confirm))fail('คำตอบยืนยันไม่ตรงกัน');await mutate([u.id],[stmt('UPDATE users SET recovery_question=?,recovery_answer_hash=? WHERE id=?',[question,await passwordHash(answer),u.id])]);return json({ok:true});}
if(action==='recovery-code'){await throttle('recovery-generate|'+u.id,10);const code=rand().slice(0,32).toUpperCase();await mutate([u.id],[stmt('UPDATE users SET recovery_hash=? WHERE id=?',[await digest(code),u.id])]);return json({ok:true,recovery_code:code.match(/.{8}/g).join('-')});}
if(action==='password'){checkPass(d.password);if(d.password!==d.password_confirm)fail('รหัสผ่านยืนยันไม่ตรงกัน');await mutate([u.id],[stmt('UPDATE users SET password_hash=?,session_version=session_version+1 WHERE id=?',[await passwordHash(d.password),u.id])]);return json({ok:true});}
if(action==='nickname'){const nickname=String(d.nickname||'').trim();if(length(nickname)>50)fail('ชื่อเล่นไม่เกิน 50 ตัวอักษร');await mutate([u.id],[stmt('UPDATE users SET nickname=? WHERE id=?',[nickname,u.id])]);return json({ok:true});}
if(action==='coworkers'){const date=url.searchParams.get('date');if(!validDate(date))fail('วันที่ไม่ถูกต้อง');return json(await getPeers(u,date));}
if(action==='coworker-options'){const date=url.searchParams.get('date');if(!validDate(date))fail('วันที่ไม่ถูกต้อง');const map=new Map(),r=await one('SELECT roster_json FROM user_roster_days WHERE user_id=? AND work_date=?',[u.id,date]);for(const p of JSON.parse(r?.roster_json||'[]'))map.set(p.employee,{employee_code:p.employee,name:nameFor(p.name,p.employee),nickname:''});for(const p of await all('SELECT employee_code,real_name FROM user_coworker_names WHERE user_id=?',[u.id]))map.set(p.employee_code,{employee_code:p.employee_code,name:p.real_name,nickname:''});for(const p of await getUsers()){const old=map.get(p.employee_code)||{employee_code:p.employee_code,name:'ยังไม่มีชื่อจริง'};map.set(p.employee_code,{...old,nickname:p.nickname});}map.delete(u.employee_code);return json({people:[...map.values()]});}
const decorate=e=>({...e,name:e.code,color:colors[e.code],allowance:rates[e.code],is_off:off.includes(e.code)?1:0});
const trainingSQL='SELECT e.id,COALESCE(p.personal_date,e.work_date) work_date,COALESCE(p.personal_title,e.title) title,p.confirmed,p.revision,t.code shift_code FROM training_events e JOIN training_participants p ON p.training_id=e.id LEFT JOIN schedules t ON t.user_id=p.user_id AND t.work_date=COALESCE(p.personal_date,e.work_date) WHERE p.user_id=? AND p.removed=0 AND COALESCE(p.personal_date,e.work_date)>=? AND COALESCE(p.personal_date,e.work_date)<? ORDER BY work_date,e.id';
if(action==='dashboard'){const month=url.searchParams.get('month')||new Date().toISOString().slice(0,7),anchor=url.searchParams.get('week')||month+'-01';if(!validMonth(month)||!validDate(anchor))fail('เดือนหรือสัปดาห์ไม่ถูกต้อง');const from=month+'-01',to=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),1)).toISOString().slice(0,10),start=new Date(anchor+'T12:00:00Z');start.setUTCDate(start.getUTCDate()-(start.getUTCDay()+6)%7);const weekFrom=start.toISOString().slice(0,10);start.setUTCDate(start.getUTCDate()+7);const weekTo=start.toISOString().slice(0,10);const rangeFrom=from<weekFrom?from:weekFrom,rangeTo=to>weekTo?to:weekTo;const [rows,allItems,notices]=await readBatch([['SELECT * FROM schedules WHERE user_id=? AND work_date>=? AND work_date<? ORDER BY work_date',[u.id,rangeFrom,rangeTo]],[trainingSQL,[u.id,rangeFrom,rangeTo]],['SELECT * FROM training_events WHERE is_team_notice=1 AND work_date>=? AND work_date<? ORDER BY work_date',[from,to]]]);const inRange=(r,a,b)=>r.work_date>=a&&r.work_date<b;const events=rows.filter(r=>inRange(r,from,to)).map(decorate),weekEvents=rows.filter(r=>inRange(r,weekFrom,weekTo)).map(decorate),items=allItems.filter(r=>inRange(r,from,to)),trainings=items.filter(t=>t.confirmed&&t.shift_code==='D'),weekTraining=allItems.filter(r=>inRange(r,weekFrom,weekTo)&&r.confirmed&&r.shift_code==='D');const s=summary(events);s.training_count=trainings.length;s.unassigned_days=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),0)).getUTCDate()-events.length;start.setUTCDate(start.getUTCDate()-1);return json({events,types,summary:s,trainings,training_items:items,training_notices:notices,week:{start:weekFrom,end:start.toISOString().slice(0,10),events:weekEvents,trainings:weekTraining}});}
if(action==='admin-data'){if(u.role!=='admin')fail('เฉพาะผู้ดูแล',403);return json({users:await all('SELECT id,name,nickname,roster_name,employee_code,role,active FROM users ORDER BY id'),types});}
if(action==='schedule'){const target=u.role==='admin'?Number(d.user_id||u.id):u.id;if(u.role!=='admin'&&d.user_id&&Number(d.user_id)!==u.id)fail('แก้กะได้เฉพาะบัญชีตัวเอง',403);if(!validDate(d.date)||!Object.hasOwn(rates,d.code))fail('วันที่หรือกะไม่ถูกต้อง');const old=await one('SELECT revision FROM schedules WHERE user_id=? AND work_date=?',[target,d.date]);if(d.expected_revision!==undefined&&Number(d.expected_revision)!==(old?.revision||0))fail('กะถูกแก้จากอีกเครื่องแล้ว กรุณารีเฟรช',409);await mutate([target],[stmt('INSERT INTO schedules(user_id,work_date,code) VALUES(?,?,?) ON CONFLICT(user_id,work_date) DO UPDATE SET code=excluded.code,revision=revision+1,import_id=NULL,coworker_json=NULL',[target,d.date,d.code])]);return json({ok:true});}
if(action==='coworker-name'||action==='coworker-remove'||action==='coworker-add'){const date=d.date,code=req(d,'employee_code',50);if(!validDate(date))fail('วันที่ไม่ถูกต้อง');const own=await one('SELECT code FROM schedules WHERE user_id=? AND work_date=?',[u.id,date]);const peers=(await getPeers(u,date,action==='coworker-remove')).people;const ops=[];if(action==='coworker-add'){const name=req(d,'real_name');if(!/^[A-Za-z0-9_-]{1,50}$/.test(code)||code===u.employee_code)fail('รหัสพนักงานไม่ถูกต้องหรือเป็นตัวเอง');if(!own||off.includes(own.code))fail('เพิ่มเพื่อนได้เฉพาะวันที่เข้ากะ');if(d.expected_code!==own.code)fail('กะเปลี่ยนแล้ว กรุณารีเฟรช',409);if(peers.some(p=>p.employee_code===code))fail('มีเพื่อนคนนี้ในรายชื่อแล้ว',409);ops.push(stmt('INSERT INTO user_added_coworkers(user_id,work_date,shift_code,employee_code,real_name) VALUES(?,?,?,?,?) ON CONFLICT(user_id,work_date,shift_code,employee_code) DO UPDATE SET real_name=excluded.real_name',[u.id,date,own.code,code,name]),stmt('INSERT INTO user_hidden_coworkers(user_id,work_date,employee_code,hidden) VALUES(?,?,?,0) ON CONFLICT(user_id,work_date,employee_code) DO UPDATE SET hidden=0',[u.id,date,code]),stmt('INSERT INTO user_coworker_names(user_id,employee_code,real_name) VALUES(?,?,?) ON CONFLICT(user_id,employee_code) DO UPDATE SET real_name=excluded.real_name',[u.id,code,name]));}else{if(!peers.some(p=>p.employee_code===code))fail('แก้ได้เฉพาะเพื่อนร่วมกะวันที่เลือก',403);if(action==='coworker-name')ops.push(stmt('INSERT INTO user_coworker_names(user_id,employee_code,real_name) VALUES(?,?,?) ON CONFLICT(user_id,employee_code) DO UPDATE SET real_name=excluded.real_name',[u.id,code,req(d,'real_name')]));else{if(typeof d.hidden!=='boolean')fail('สถานะไม่ถูกต้อง');ops.push(stmt('INSERT INTO user_hidden_coworkers(user_id,work_date,employee_code,hidden) VALUES(?,?,?,?) ON CONFLICT(user_id,work_date,employee_code) DO UPDATE SET hidden=excluded.hidden',[u.id,date,code,Number(d.hidden)]));}}await mutate([u.id],ops);return json({ok:true});}
if(action==='training-add'){const title=req(d,'title'),dates=d.dates===undefined?[d.date]:d.dates;if(!Array.isArray(dates)||!dates.length||dates.length>60||dates.some(x=>!validDate(x))||new Set(dates).size!==dates.length||typeof d.confirmed!=='boolean')fail('กรุณาเลือกวันอบรม 1–60 วันโดยไม่ซ้ำ');if(d.user_id&&Number(d.user_id)!==u.id)fail('เพิ่มอบรมได้เฉพาะบัญชีตัวเอง',403);const datesJSON=JSON.stringify(dates);const [shifts,existing]=await readBatch([['SELECT work_date,code FROM schedules WHERE user_id=? AND work_date IN (SELECT value FROM json_each(?))',[u.id,datesJSON]],['SELECT COALESCE(p.personal_date,e.work_date) work_date FROM training_events e JOIN training_participants p ON p.training_id=e.id WHERE p.user_id=? AND p.removed=0 AND COALESCE(p.personal_date,e.work_date) IN (SELECT value FROM json_each(?)) AND COALESCE(p.personal_title,e.title)=?',[u.id,datesJSON,title]]]);if(d.confirmed){const invalid=dates.filter(date=>shifts.find(s=>s.work_date===date)?.code!=='D');if(invalid.length)fail('ยืนยันได้เฉพาะวันที่เป็นกะ D กรุณาตรวจ: '+invalid.join(', '));}if(existing.length)fail('มีวันและหัวข้ออบรมนี้แล้ว: '+existing.map(t=>t.work_date).join(', '),409);await mutate([u.id],[stmt('INSERT OR IGNORE INTO training_events(work_date,title,is_team_notice) SELECT value,?,0 FROM json_each(?)',[title,datesJSON]),stmt('INSERT INTO training_participants(training_id,user_id,confirmed) SELECT e.id,?,? FROM training_events e JOIN json_each(?) d ON e.work_date=d.value WHERE e.title=? ON CONFLICT(training_id,user_id) DO UPDATE SET confirmed=excluded.confirmed,removed=0,personal_date=NULL,personal_title=NULL,revision=revision+1',[u.id,Number(d.confirmed),datesJSON,title])]);return json({ok:true,count:dates.length});}
if(action==='training-edit'||action==='training-remove'){const id=Number(d.id),event=await one('SELECT * FROM training_events WHERE id=?',[id]),p=await one('SELECT * FROM training_participants WHERE training_id=? AND user_id=?',[id,u.id]);if(!event||(!p&&!event.is_team_notice)||action==='training-remove'&&!p||action==='training-edit'&&p?.removed)fail('ทำได้เฉพาะรายการอบรมของคุณ',403);if(Number(d.expected_revision)!==(p?.revision||0))fail('รายการเปลี่ยนแล้ว กรุณารีเฟรช',409);if(action==='training-remove'){if(typeof d.removed!=='boolean')fail('สถานะไม่ถูกต้อง');await mutate([u.id],[stmt('UPDATE training_participants SET removed=?,revision=revision+1 WHERE training_id=? AND user_id=?',[Number(d.removed),id,u.id])]);return json({ok:true,revision:p.revision+1});}const title=req(d,'title');if(!validDate(d.date)||typeof d.confirmed!=='boolean')fail('วันหรือสถานะไม่ถูกต้อง');if(d.confirmed&&(await one('SELECT code FROM schedules WHERE user_id=? AND work_date=?',[u.id,d.date]))?.code!=='D')fail('ยืนยันได้เฉพาะวันที่เป็นกะ D');await mutate([u.id],[stmt('INSERT INTO training_participants(training_id,user_id,personal_date,personal_title,confirmed) VALUES(?,?,?,?,?) ON CONFLICT(training_id,user_id) DO UPDATE SET personal_date=excluded.personal_date,personal_title=excluded.personal_title,confirmed=excluded.confirmed,revision=revision+1',[id,u.id,d.date,title,Number(d.confirmed)])]);return json({ok:true});}
if(action==='prepare-import'){
 if(!validMonth(d.month)||!Array.isArray(d.roster?.rows)||d.roster.rows.length>5000)fail('เดือนหรือข้อมูลรูปไม่ถูกต้อง');const users=await getUsers(),seen=new Set(),names=await all('SELECT employee_code,real_name FROM user_coworker_names WHERE user_id=?',[u.id]),raw=[];for(const r of d.roster.rows){const employee=String(r.employee||'').trim(),name=String(r.name||'').trim();if(!/^[A-Za-z0-9_-]{1,50}$/.test(employee)||!validDate(r.date)||!r.date.startsWith(d.month+'-')||!(Object.hasOwn(rates,r.code)||r.code==='UNKNOWN')||length(name)>150)fail('กรุณาตรวจรหัสพนักงาน วันที่ และกะในผลอ่านรูป');const key=employee+'|'+r.date;if(seen.has(key))fail('แถวกะซ้ำ');seen.add(key);raw.push({employee,name:names.find(n=>n.employee_code===employee)?.real_name||name,date:r.date,code:r.code});}
 const existing=await all('SELECT user_id,work_date,revision FROM schedules WHERE work_date>=? AND work_date<=?',[d.month+'-01',d.month+'-31']),revision_snapshot=Object.fromEntries(existing.map(x=>[x.user_id+'|'+x.work_date,x.revision]));const rows=[];for(const r of raw){const user=users.find(user=>user.employee_code===r.employee);if(u.role!=='admin'&&user?.id!==u.id)continue;const revision=user?revision_snapshot[user.id+'|'+r.date]||0:0;const coworkers=off.includes(r.code)?[]:raw.filter(p=>p.date===r.date&&p.code===r.code&&p.employee!==r.employee).map(p=>({employee_code:p.employee,name:nameFor(p.name,p.employee)}));rows.push({...r,source_key:r.employee+'|'+r.date,user_id:user?.id||null,uncertain:true,coworkers,existing:!!revision,existing_revision:revision});}if(!rows.length)fail('ไม่พบรหัสพนักงานของคุณในรูป');if(!Array.isArray(d.roster.trainings||[])||(d.roster.trainings||[]).length>100)fail('รายการอบรมมากเกินไป');const trainings=(d.roster.trainings||[]).map(t=>{if(!validDate(t.date)||!t.date.startsWith(d.month+'-')||length(String(t.title||''))>150)fail('รายการอบรมไม่ถูกต้อง');const ids=rows.filter(r=>r.date===t.date&&r.code==='D'&&r.user_id).map(r=>r.user_id);return {...t,user_ids:[...new Set(ids)],uncertain:true};});const result=await run('INSERT INTO imports(uploaded_by,month,draft_json) VALUES(?,?,?)',[u.id,d.month,JSON.stringify({rows,trainings,team_roster:raw,revision_snapshot})]);return json({id:result.meta.last_row_id,month:d.month,rows,trainings,users:u.role==='admin'?users:[safeUser(u)],warnings:['ตรวจรหัสกะ วัน และชื่อก่อนบันทึก ชื่อที่จำไว้จับคู่ตามรหัสพนักงาน']});
}
async function trainingStatements(t,allowed,planned=null,isAdmin=false){if(!validDate(t.date)||!String(t.title||'').trim()||length(String(t.title))>150||!Array.isArray(t.user_ids)||(!t.user_ids.length&&!isAdmin))fail('กรุณาตรวจวัน หัวข้อ และผู้เข้าร่วม');const ids=[...new Set(t.user_ids.map(Number))];for(const id of ids){if(!allowed.includes(id))fail('ไม่มีสิทธิ์กำหนดอบรมบัญชีนี้',403);const code=planned?.find(r=>r.user_id===id&&r.date===t.date)?.code||(await one('SELECT code FROM schedules WHERE user_id=? AND work_date=?',[id,t.date]))?.code;if(code!=='D')fail('ผู้เข้าอบรมต้องเป็นกะ D ในวันอบรม');}const ops=[stmt('INSERT INTO training_events(work_date,title,is_team_notice) VALUES(?,?,?) ON CONFLICT(work_date,title) DO UPDATE SET is_team_notice=MAX(is_team_notice,excluded.is_team_notice)',[t.date,t.title.trim(),Number(isAdmin)])];for(const id of ids)ops.push(stmt('INSERT OR IGNORE INTO training_participants(training_id,user_id) VALUES((SELECT id FROM training_events WHERE work_date=? AND title=?),?)',[t.date,t.title.trim(),id]));return ops;}
if(action==='commit-import'){
 const imp=await one('SELECT * FROM imports WHERE id=? AND uploaded_by=?',[Number(d.id),u.id]);if(!imp||imp.status!=='draft')fail('รายการนำเข้านี้ใช้ไม่ได้',409);const draft=JSON.parse(imp.draft_json),users=await getUsers(),allowed=u.role==='admin'?users.map(x=>x.id):[u.id],seen=new Set(),ops=[],ids=[u.id];if(!Array.isArray(d.rows)||!d.rows.length||d.rows.length>5000||!Array.isArray(d.trainings)||d.trainings.length>100)fail('ตารางไม่ถูกต้อง');const peerNames=d.coworker_names||{},permitted=new Set(draft.rows.flatMap(r=>r.coworkers.map(p=>p.employee_code)));for(const [code,name] of Object.entries(peerNames))if(!permitted.has(code)||typeof name!=='string'||!name.trim()||length(name)>150)fail('ชื่อร่วมกะต้องตรงกับคนที่พบในตาราง');
 const current=await all('SELECT user_id,work_date,revision FROM schedules WHERE work_date>=? AND work_date<=?',[imp.month+'-01',imp.month+'-31']),currentRevisions=new Map(current.map(x=>[x.user_id+'|'+x.work_date,x.revision])),usedSources=new Set(),planned=[],writeRows=[],rosterRows=[];
 for(const r of d.rows){const id=Number(r.user_id),key=id+'|'+r.date;if(!allowed.includes(id)||!validDate(r.date)||!r.date.startsWith(imp.month+'-')||!Object.hasOwn(rates,r.code)||seen.has(key))fail('บัญชี วัน หรือกะไม่ถูกต้อง/ซ้ำ');seen.add(key);ids.push(id);
 const original=r.source_key?draft.rows.find(x=>x.source_key===r.source_key):draft.rows.find(x=>x.user_id===id&&x.date===r.date);if(!original||usedSources.has(original.source_key||original.employee+'|'+original.date))fail('แถวนี้ไม่อยู่ในผลอ่านรูปเดิมหรือซ้ำ');usedSources.add(original.source_key||original.employee+'|'+original.date);
 if(u.role!=='admin'&&original.user_id!==u.id)fail('แก้ได้เฉพาะกะของคุณ',403);const expected=draft.revision_snapshot?.[key]??(original.user_id===id&&original.date===r.date?original.existing_revision:0),old=currentRevisions.get(key)||0;if(old!==expected)fail('กะเปลี่ยนจากอีกเครื่อง กรุณานำเข้าใหม่',409);if(old&&!d.overwrite)fail('มีกะเดิมอยู่แล้ว กรุณาเลือกแทนที่กะเดิม');
 const peers=original.code===r.code?original.coworkers.map(p=>({...p,name:peerNames[p.employee_code]?.trim()||p.name})):[];if(peers.some(p=>nameFor(p.name,p.employee_code)==='ยังไม่มีชื่อจริง'))fail('กรุณากรอกชื่อจริงของเพื่อนร่วมกะที่อ่านไม่ออก');planned.push({...r,user_id:id,source_employee:original.employee,source_date:original.date});writeRows.push({id,date:r.date,code:r.code,import_id:imp.id,peers:JSON.stringify(peers)}); }
 for(const r of planned){const roster=draft.team_roster.filter(x=>x.date===r.source_date).map(x=>{const corrected=planned.find(p=>p.source_employee===x.employee&&p.source_date===x.date);return {...x,date:r.date,employee:corrected?users.find(u=>u.id===corrected.user_id).employee_code:x.employee,code:corrected?.code||x.code,name:peerNames[x.employee]?.trim()||x.name};});rosterRows.push({id:r.user_id,date:r.date,roster:JSON.stringify(roster)});}
 const appendChunks=(sql,rows)=>{let chunk=[],bytes=2;for(const row of rows){const size=enc.encode(JSON.stringify(row)).length+1;if(bytes+size>700000&&chunk.length){ops.push(stmt(sql,[JSON.stringify(chunk)]));chunk=[];bytes=2;}chunk.push(row);bytes+=size;}if(chunk.length)ops.push(stmt(sql,[JSON.stringify(chunk)]));};
 appendChunks("INSERT INTO schedules(user_id,work_date,code,import_id,coworker_json) SELECT json_extract(value,'$.id'),json_extract(value,'$.date'),json_extract(value,'$.code'),json_extract(value,'$.import_id'),json_extract(value,'$.peers') FROM json_each(?) WHERE 1 ON CONFLICT(user_id,work_date) DO UPDATE SET code=excluded.code,import_id=excluded.import_id,coworker_json=excluded.coworker_json,revision=revision+1",writeRows);
 appendChunks("INSERT INTO user_roster_days(user_id,work_date,roster_json) SELECT json_extract(value,'$.id'),json_extract(value,'$.date'),json_extract(value,'$.roster') FROM json_each(?) WHERE 1 ON CONFLICT(user_id,work_date) DO UPDATE SET roster_json=excluded.roster_json",rosterRows);
 for(const [code,name] of Object.entries(peerNames))ops.push(stmt('INSERT INTO user_coworker_names(user_id,employee_code,real_name) VALUES(?,?,?) ON CONFLICT(user_id,employee_code) DO UPDATE SET real_name=excluded.real_name',[u.id,code,name.trim()]));for(const t of d.trainings){if(!t.date?.startsWith(imp.month+'-'))fail('วันอบรมผิดเดือน');ids.push(...(t.user_ids||[]).map(Number));ops.push(...await trainingStatements(t,allowed,planned,u.role==='admin'));}ops.push(stmt("UPDATE imports SET status='committed',draft_json='{}' WHERE id=?",[imp.id]));await mutate(ids,ops);return json({ok:true,count:d.rows.length,training_count:d.trainings.length});
}
if(u.role!=='admin')fail('เฉพาะผู้ดูแล',403);
if(action==='create-user'){const code=req(d,'employee_code',50),name=req(d,'name'),roster=req(d,'roster_name');checkPass(d.password);if(await one('SELECT id FROM users WHERE employee_code=? OR roster_name=?',[code,roster]))fail('รหัสหรือชื่อในตารางซ้ำ');await run('INSERT INTO users(employee_code,name,roster_name,password_hash,nickname) VALUES(?,?,?,?,?)',[code,name,roster,await passwordHash(d.password),name.slice(0,50)]);return json({ok:true});}
if(action==='user-settings'){const id=Number(d.user_id),roster=req(d,'roster_name'),target=await one('SELECT * FROM users WHERE id=?',[id]);if(!target)fail('ไม่พบบัญชี');if(id===u.id&&!d.active)fail('ไม่สามารถปิดบัญชีตนเอง');await mutate([id],[stmt('UPDATE users SET roster_name=?,active=?,session_version=session_version+1 WHERE id=?',[roster,Number(!!d.active),id])]);return json({ok:true});}
if(action==='training'){const users=await getUsers(),ops=await trainingStatements(d,users.map(x=>x.id),null,true);await mutate([u.id,...d.user_ids],ops);return json({ok:true});}
if(action==='delete-training'){const id=Number(d.id),parts=await all('SELECT user_id FROM training_participants WHERE training_id=?',[id]);await mutate([u.id,...parts.map(x=>x.user_id)],[stmt('DELETE FROM training_events WHERE id=?',[id])]);return json({ok:true});}
fail('ไม่พบรายการ',404);
}catch(e){if(!e.status)console.error('ShiftTrack request failed',e);return Response.json({error:e.status?e.message:'ระบบยังทำรายการไม่ได้ กรุณาลองใหม่'},{status:e.status||500,headers:{'Cache-Control':'no-store',...extra}});}}
